from __future__ import annotations

import contextlib
import math
import os
import shutil
import tempfile
from collections.abc import Iterator
from pathlib import Path

import numpy as np

from genrecon_worker.schema import InferenceRequest


def _qvec_to_rotation(qvec: np.ndarray) -> np.ndarray:
    qvec = qvec / np.linalg.norm(qvec)
    w, x, y, z = qvec
    return np.array(
        [
            [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
            [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
            [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
        ],
        dtype=np.float64,
    )


def _rotation_to_qvec(rotation: np.ndarray) -> np.ndarray:
    matrix = np.empty((4, 4), dtype=np.float64)
    matrix[0, 0] = rotation[0, 0] - rotation[1, 1] - rotation[2, 2]
    matrix[1, 1] = rotation[1, 1] - rotation[0, 0] - rotation[2, 2]
    matrix[2, 2] = rotation[2, 2] - rotation[0, 0] - rotation[1, 1]
    matrix[3, 3] = rotation[0, 0] + rotation[1, 1] + rotation[2, 2]
    matrix[0, 1] = matrix[1, 0] = rotation[0, 1] + rotation[1, 0]
    matrix[0, 2] = matrix[2, 0] = rotation[2, 0] + rotation[0, 2]
    matrix[0, 3] = matrix[3, 0] = rotation[1, 2] - rotation[2, 1]
    matrix[1, 2] = matrix[2, 1] = rotation[1, 2] + rotation[2, 1]
    matrix[1, 3] = matrix[3, 1] = rotation[2, 0] - rotation[0, 2]
    matrix[2, 3] = matrix[3, 2] = rotation[0, 1] - rotation[1, 0]
    matrix /= 3.0
    eigenvalues, eigenvectors = np.linalg.eigh(matrix)
    qvec = eigenvectors[[3, 0, 1, 2], np.argmax(eigenvalues)]
    if qvec[0] < 0:
        qvec *= -1
    return qvec / np.linalg.norm(qvec)


def read_points(path: Path) -> tuple[list[list[str]], np.ndarray]:
    rows: list[list[str]] = []
    xyz: list[list[float]] = []
    with path.open("r", encoding="utf-8") as file:
        for line in file:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            parts = stripped.split()
            if len(parts) < 8:
                raise RuntimeError(f"malformed COLMAP points3D row: {stripped}")
            point = [float(parts[1]), float(parts[2]), float(parts[3])]
            if not all(math.isfinite(value) for value in point):
                raise RuntimeError("COLMAP sparse points contain non-finite coordinates")
            rows.append(parts)
            xyz.append(point)
    if len(xyz) < 4:
        raise RuntimeError("GenRecon requires at least four finite COLMAP sparse points")
    return rows, np.asarray(xyz, dtype=np.float64)


def _deterministic_axis(vector: np.ndarray) -> np.ndarray:
    vector = vector.copy()
    pivot = int(np.argmax(np.abs(vector)))
    if vector[pivot] < 0:
        vector *= -1
    return vector


def working_transform(
    points: np.ndarray,
    strategy: str,
) -> tuple[np.ndarray, np.ndarray, dict[str, object]]:
    if strategy == "identity":
        forward = np.eye(4, dtype=np.float64)
    else:
        center = np.median(points, axis=0)
        centered = points - center
        covariance = centered.T @ centered / max(len(centered) - 1, 1)
        _, eigenvectors = np.linalg.eigh(covariance)
        x_axis = _deterministic_axis(eigenvectors[:, 2])
        z_axis = _deterministic_axis(eigenvectors[:, 0])
        y_axis = np.cross(z_axis, x_axis)
        y_axis /= np.linalg.norm(y_axis)
        x_axis = np.cross(y_axis, z_axis)
        x_axis /= np.linalg.norm(x_axis)
        z_axis /= np.linalg.norm(z_axis)
        rotation = np.stack([x_axis, y_axis, z_axis])
        if np.linalg.det(rotation) < 0:
            rotation[1] *= -1
        forward = np.eye(4, dtype=np.float64)
        forward[:3, :3] = rotation
        forward[:3, 3] = -(rotation @ center)
    inverse = np.linalg.inv(forward)
    error = float(np.max(np.abs(forward @ inverse - np.eye(4))))
    record = {
        "strategy": strategy,
        "matrix_colmap_to_working": forward.tolist(),
        "matrix_working_to_colmap": inverse.tolist(),
        "determinant": float(np.linalg.det(forward[:3, :3])),
        "roundtrip_max_error": error,
        "semantic_status": "internal_unoriented_preprocessing",
    }
    return forward, inverse, record


def _write_transformed_points(
    source: Path,
    destination: Path,
    rows: list[list[str]],
    points: np.ndarray,
    forward: np.ndarray,
) -> None:
    transformed = (forward[:3, :3] @ points.T).T + forward[:3, 3]
    header = [
        "# GenRecon working-frame COLMAP points generated by Reconevery",
        "# Coordinates are internal unoriented preprocessing, not metric or gravity aligned.",
    ]
    lines = []
    for parts, point in zip(rows, transformed, strict=True):
        parts[1:4] = [format(float(value), ".17g") for value in point]
        lines.append(" ".join(parts))
    destination.write_text("\n".join([*header, *lines]) + "\n", encoding="utf-8")


def _write_transformed_images(
    source: Path,
    destination: Path,
    forward: np.ndarray,
) -> None:
    lines = source.read_text(encoding="utf-8").splitlines()
    output: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        if stripped.startswith("#"):
            output.append(line)
            index += 1
            continue
        if not stripped:
            output.append(line)
            index += 1
            continue
        parts = stripped.split(maxsplit=9)
        if len(parts) != 10:
            raise RuntimeError(f"malformed COLMAP images row: {stripped}")
        qvec = np.asarray([float(value) for value in parts[1:5]], dtype=np.float64)
        tvec = np.asarray([float(value) for value in parts[5:8]], dtype=np.float64)
        rotation = _qvec_to_rotation(qvec)
        world_to_camera = np.eye(4, dtype=np.float64)
        world_to_camera[:3, :3] = rotation
        world_to_camera[:3, 3] = tvec
        camera_to_world_original = np.linalg.inv(world_to_camera)
        camera_to_world_working = forward @ camera_to_world_original
        transformed_world_to_camera = np.linalg.inv(camera_to_world_working)
        transformed_qvec = _rotation_to_qvec(transformed_world_to_camera[:3, :3])
        transformed_tvec = transformed_world_to_camera[:3, 3]
        output.append(
            " ".join(
                [
                    parts[0],
                    *[format(float(value), ".17g") for value in transformed_qvec],
                    *[format(float(value), ".17g") for value in transformed_tvec],
                    parts[8],
                    parts[9],
                ]
            )
        )
        index += 1
        if index >= len(lines):
            raise RuntimeError("COLMAP images header has no following POINTS2D row")
        output.append(lines[index])
        index += 1
    destination.write_text("\n".join(output) + "\n", encoding="utf-8")


def _link_or_copy(source: Path, destination: Path) -> None:
    try:
        os.link(source, destination)
    except OSError:
        shutil.copy2(source, destination)


@contextlib.contextmanager
def prepared_scene(
    root: Path,
    request: InferenceRequest,
) -> Iterator[tuple[Path, np.ndarray, dict[str, object], np.ndarray]]:
    package_root = root / "camera" / "genrecon_package"
    rows, points = read_points(package_root / "points3D.txt")
    forward, inverse, transform = working_transform(
        points,
        request.working_transform_strategy,
    )
    temporary = Path(
        tempfile.mkdtemp(prefix=".genrecon-input-", dir=root / "reconstruction" / "global")
    )
    try:
        rgb = temporary / "rgb"
        colmap = temporary / "colmap"
        rgb.mkdir(parents=True)
        colmap.mkdir()
        shutil.copy2(package_root / "cameras.txt", colmap / "cameras.txt")
        _write_transformed_images(
            package_root / "images.txt",
            colmap / "images.txt",
            forward,
        )
        _write_transformed_points(
            package_root / "points3D.txt",
            colmap / "points3D.txt",
            rows,
            points,
            forward,
        )
        for frame_id in request.eligible_frame_ids:
            source = root / request.normalized_frame_paths[frame_id]
            destination = rgb / source.name
            _link_or_copy(source, destination)
            if destination.stat().st_size != source.stat().st_size:
                raise RuntimeError(f"prepared GenRecon frame size changed: {frame_id}")
        yield temporary, inverse, transform, points
    finally:
        shutil.rmtree(temporary, ignore_errors=True)
