__version__ = "0.1.0"

OFFICIAL_APRILTAG_REPOSITORY = "https://github.com/AprilRobotics/apriltag"
OFFICIAL_APRILTAG_COMMIT = "0e16a12dd380fd607e4afd54712ee9b1ffb9ec8f"
OFFICIAL_APRILTAG_LICENSE = "BSD-2-Clause"
OFFICIAL_APRILTAG_VERSION = "3.4.5"

__all__ = [
    "OFFICIAL_APRILTAG_COMMIT",
    "OFFICIAL_APRILTAG_LICENSE",
    "OFFICIAL_APRILTAG_REPOSITORY",
    "OFFICIAL_APRILTAG_VERSION",
    "__version__",
]
