from pathlib import Path

from recon2sim.artifacts import (
    AlignmentCandidateManifest,
    AlignmentDatasetSplit,
    AlignmentIterationManifest,
    ArticulatedAssetIndex,
    ArticulatedCandidateManifest,
    ArticulatedCandidateSelection,
    ArticulatedEligibilityArtifact,
    ArticulatedEvaluationManifest,
    ArticulatedLinkAssignmentManifest,
    ArticulatedPartStateGeometryManifest,
    ArticulatedRetrievalResult,
    ArticulationCaptureManifest,
    ArticulationDiagnostics,
    ArticulationEvidenceSplit,
    ArticulationFittingManifest,
    ArticulationPartPromptManifest,
    ArticulationPreviewManifest,
    ArticulationStateAlignmentArtifact,
    CameraMeshAlignmentArtifact,
    CameraMeshAlignmentDiagnostics,
    CameraMeshAlignmentPreviewManifest,
    CameraMeshAlignmentRequest,
    CameraMeshAlignmentResult,
    CameraMeshAlignmentWorkerManifest,
    CandidateEvaluationManifest,
    CandidateEvaluationRequest,
    CandidateGenerationManifest,
    CandidateRegistrationManifest,
    CandidateRegistrationRequest,
    CandidateSelectionArtifact,
    CompletionCropManifest,
    CompletionDiagnostics,
    CompletionEligibilityArtifact,
    CompletionEvidencePackage,
    CompletionEvidencePreparationRequest,
    CompletionEvidenceSplit,
    CompletionWorkerManifest,
    DenseDepthManifest,
    DenseFusionArtifact,
    DenseMVSDiagnostics,
    DenseMVSRequest,
    DenseMVSWorkerManifest,
    DenseUndistortionManifest,
    DenseWorkspaceManifest,
    EndToEndConsistencyReport,
    GenReconCameraPackageManifest,
    GenReconCheckpointManifest,
    GenReconInferenceRequest,
    GenReconWorkerManifest,
    GlobalSceneDiagnostics,
    GlobalSceneReconstructionArtifact,
    MeasuredGeneratedComparisonArtifact,
    MeasuredObjectDiagnostics,
    MeasuredObjectGeometryArtifact,
    MeasuredObjectGeometryRequest,
    MeasuredObjectWorkerManifest,
    MeasuredPartMotionArtifact,
    ObjectLiftingAlignmentComparison,
    ObjectSurfaceDiagnostics,
    ObjectSurfaceEvidenceArtifact,
    ObjectSurfaceLiftingRequest,
    ObjectSurfaceMethodComparison,
    ObjectSurfaceWorkerManifest,
    ParticulateCandidateRequest,
    ParticulateWorkerManifest,
    Phase4_2ConsistencyReport,
    Phase4ConsistencyReport,
    Phase5AConsistencyReport,
    Phase5BConsistencyReport,
    Phase5CConsistencyReport,
    Sam3InferenceRequest,
    SegmentationPromptManifest,
    SegmentationTrackingArtifact,
    SparseDepthObservationManifest,
    TransformChainAudit,
)
from recon2sim.ir import SceneIR
from recon2sim.storage import atomic_write_json

atomic_write_json(Path("schemas/scene_ir.schema.json"), SceneIR.model_json_schema())
atomic_write_json(
    Path("schemas/segmentation_prompts.schema.json"),
    SegmentationPromptManifest.model_json_schema(),
)
atomic_write_json(
    Path("schemas/sam3_inference_request.schema.json"),
    Sam3InferenceRequest.model_json_schema(),
)
atomic_write_json(
    Path("schemas/segmentation_tracking.schema.json"),
    SegmentationTrackingArtifact.model_json_schema(),
)
for filename, model in {
    "genrecon_camera_package.schema.json": GenReconCameraPackageManifest,
    "genrecon_checkpoints.schema.json": GenReconCheckpointManifest,
    "genrecon_inference_request.schema.json": GenReconInferenceRequest,
    "genrecon_worker_manifest.schema.json": GenReconWorkerManifest,
    "global_scene_reconstruction.schema.json": GlobalSceneReconstructionArtifact,
    "global_scene_diagnostics.schema.json": GlobalSceneDiagnostics,
    "phase3_e2e_consistency.schema.json": EndToEndConsistencyReport,
    "object_surface_lifting_request.schema.json": ObjectSurfaceLiftingRequest,
    "object_surface_worker_manifest.schema.json": ObjectSurfaceWorkerManifest,
    "object_surface_evidence.schema.json": ObjectSurfaceEvidenceArtifact,
    "object_surface_diagnostics.schema.json": ObjectSurfaceDiagnostics,
    "object_surface_method_comparison.schema.json": ObjectSurfaceMethodComparison,
    "camera_mesh_alignment.schema.json": CameraMeshAlignmentArtifact,
    "phase4_object_surface_consistency.schema.json": Phase4ConsistencyReport,
    "camera_mesh_alignment_request.schema.json": CameraMeshAlignmentRequest,
    "camera_mesh_alignment_worker_manifest.schema.json": (CameraMeshAlignmentWorkerManifest),
    "camera_mesh_alignment_result.schema.json": CameraMeshAlignmentResult,
    "camera_mesh_alignment_diagnostics.schema.json": CameraMeshAlignmentDiagnostics,
    "camera_mesh_alignment_previews.schema.json": CameraMeshAlignmentPreviewManifest,
    "transform_chain_audit.schema.json": TransformChainAudit,
    "sparse_depth_observations.schema.json": SparseDepthObservationManifest,
    "alignment_dataset_split.schema.json": AlignmentDatasetSplit,
    "alignment_candidates.schema.json": AlignmentCandidateManifest,
    "alignment_iterations.schema.json": AlignmentIterationManifest,
    "object_lifting_alignment_comparison.schema.json": (ObjectLiftingAlignmentComparison),
    "phase4_2_camera_mesh_alignment.schema.json": Phase4_2ConsistencyReport,
    "dense_mvs_request.schema.json": DenseMVSRequest,
    "dense_mvs_worker_manifest.schema.json": DenseMVSWorkerManifest,
    "dense_workspace_manifest.schema.json": DenseWorkspaceManifest,
    "dense_undistortion_manifest.schema.json": DenseUndistortionManifest,
    "dense_depth_manifest.schema.json": DenseDepthManifest,
    "dense_fusion.schema.json": DenseFusionArtifact,
    "dense_mvs_diagnostics.schema.json": DenseMVSDiagnostics,
    "measured_object_geometry_request.schema.json": MeasuredObjectGeometryRequest,
    "measured_object_worker_manifest.schema.json": MeasuredObjectWorkerManifest,
    "measured_object_geometry.schema.json": MeasuredObjectGeometryArtifact,
    "measured_object_diagnostics.schema.json": MeasuredObjectDiagnostics,
    "measured_generated_comparison.schema.json": MeasuredGeneratedComparisonArtifact,
    "phase5a_measured_geometry.schema.json": Phase5AConsistencyReport,
    "completion_eligibility.schema.json": CompletionEligibilityArtifact,
    "completion_evidence_split.schema.json": CompletionEvidenceSplit,
    "completion_crop_manifest.schema.json": CompletionCropManifest,
    "completion_evidence_request.schema.json": CompletionEvidencePreparationRequest,
    "completion_evidence_package.schema.json": CompletionEvidencePackage,
    "completion_worker_manifest.schema.json": CompletionWorkerManifest,
    "completion_generation_manifest.schema.json": CandidateGenerationManifest,
    "completion_registration_request.schema.json": CandidateRegistrationRequest,
    "completion_registration_manifest.schema.json": CandidateRegistrationManifest,
    "completion_evaluation_request.schema.json": CandidateEvaluationRequest,
    "completion_evaluation_manifest.schema.json": CandidateEvaluationManifest,
    "completion_selection.schema.json": CandidateSelectionArtifact,
    "completion_diagnostics.schema.json": CompletionDiagnostics,
    "phase5b_rigid_completion.schema.json": Phase5BConsistencyReport,
    "articulated_eligibility.schema.json": ArticulatedEligibilityArtifact,
    "articulation_part_prompts.schema.json": ArticulationPartPromptManifest,
    "articulation_capture.schema.json": ArticulationCaptureManifest,
    "articulation_state_alignment.schema.json": ArticulationStateAlignmentArtifact,
    "articulated_part_state_geometry.schema.json": ArticulatedPartStateGeometryManifest,
    "measured_part_motion.schema.json": MeasuredPartMotionArtifact,
    "articulation_evidence_split.schema.json": ArticulationEvidenceSplit,
    "articulated_asset_index.schema.json": ArticulatedAssetIndex,
    "articulated_retrieval.schema.json": ArticulatedRetrievalResult,
    "particulate_candidate_request.schema.json": ParticulateCandidateRequest,
    "particulate_worker_manifest.schema.json": ParticulateWorkerManifest,
    "articulated_candidate_manifest.schema.json": ArticulatedCandidateManifest,
    "articulated_link_assignments.schema.json": ArticulatedLinkAssignmentManifest,
    "articulation_fitting.schema.json": ArticulationFittingManifest,
    "articulation_evaluation.schema.json": ArticulatedEvaluationManifest,
    "articulation_selection.schema.json": ArticulatedCandidateSelection,
    "articulation_diagnostics.schema.json": ArticulationDiagnostics,
    "articulation_previews.schema.json": ArticulationPreviewManifest,
    "phase5c_articulated_reconstruction.schema.json": Phase5CConsistencyReport,
}.items():
    atomic_write_json(Path("schemas") / filename, model.model_json_schema())
